name: Daily Leme Claim

on:
  schedule:
    - cron: '30 2 * * *' # ساعت ۶ صبح به وقت ایران
  workflow_dispatch: # دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        env:
          LEME_USER: ${{ secrets.LEME_USER }}
          LEME_PASS: ${{ secrets.LEME_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: "8404377559"
        run: python claim_script.py
